### PR TITLE
Bumps version to 1.0.0

### PR DESCRIPTION
**Pull request by mitchhentges**
See https://github.com/mozilla-releng/releng-rfcs/issues/19

### CODE REVIEW

**Comment by mitchhentges** [comment]
Thanks! :)
I've discovered that we don't have write access to merge this, but Aki is a safe bet :tada:

**Comment by escapewindow** [comment]
Do you have it from here, or do you want some help crafting a release?

**Comment by JohanLorenzo** [comment]
@mitchhentges be careful with this project. You need the git submodules initialized https://github.com/mozilla-releng/pushsnapscript#get-the-code. Otherwise, the next pushsnap run will fail because of a missing dependency

**Comment by mitchhentges** [comment]
I can release it from here :+1:
Thanks for the heads-up Johan :)

**Comment by mitchhentges** [comment]
@escapewindow I lied, I don't have access to `pushsnapscript` on Pypi:

> HTTPError: 403 Client Error: The user 'mitchhentgesmozilla' isn't allowed to upload to project 'pushsnapscript'. See https://pypi.org/help/#project-name for more information. for url: https://upload.pypi.org/legacy/

FWIW, for review, what I was _going_ to do for releasing was:
```
git fetch upstream
git checkout 92078ccc303ab42d05a9ec7201291bc8593eef02
git submodule init
git submodule update
rm -rf dist && python setup.py sdist bdist_wheel
# twine
# upload to puppet
```

**Comment by JohanLorenzo** [comment]
Oops, I just gave you the permissions to push to Pypi, @mitchhentges. The commands you showed are correct, to me.

**Pull request merged**
